### ISSUE TITLE
Support exploring metadata from Python source code

### ISSUE THREAD

**Issue by psss** [psss/fmf#103]
@jscotka has experimented with storing `fmf` metadata in python decorators:

 * https://github.com/jscotka/fmf_metadata

It could be useful to add support for such parsing directly to `fmf`. By default, `*.fmf` files would be checked only, a dedicated option could be used to enabled parsing `*.py` files as well.

    fmf --extension py

Metadata could be combined from both sources:

    fmf --extension fmf --extension py

In `tmt` the discover step could support a relevant option to enable such behaviour:

    discover:
        how: fmf
        extension: [fmf, py]

**Comment by jscotka** [comment]
After small brainstorming, that would be also nice that FMF could use any file with metadata, although inside code, be able to find special prefixed strings inside comments like: `runtest.sh`
```
#!/bin/bash
# :FMF: summary: This is a summary of the test
# :FMF: duration: 1m
# :FMF: environment+: {TEST_OS: linux}

/bin/true
```
will seems like FMF file: `runtest.sh.fmf`
```
summary: This is a summary of the test
duration: 1m
environment+: {TEST_OS: linux}
```

and it can work like searching strings inside file `re.search(":FMF:(\1)", line).group(1)`
but theoretically, it would be harder when using virtual hierarchy
 - with parametrized tests
 - more tests in one file like python unittest
in this case, it is important to know the test structure and semantics of the language.

so something like python docstring still possible, but harder to use, or better to say, important to write semantics for every language we want.

But as the opposite side, I like the idea of decorators, because there works automatic completion, semantics check, so it is clean and well structured as python code

**Comment by jscotka** [comment]
done question to pytest upstream, if able to do external python exploring:

https://github.com/pytest-dev/pytest/discussions/8554

**Comment by jscotka** [comment]
PoC inside FMF: https://github.com/psss/fmf/pull/136
it uses code from mentioned project

**Comment by LecrisUT** [comment]
This might still be relevant, but we still do not know for sure how to handle it. We'll check back on it next week
